services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=govtrack
      - POSTGRES_PASSWORD=govtrack123
      - POSTGRES_DB=govtrack
    ports:
      - "5432:5432"
    networks:
      - govtrack-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - govtrack-network

  postgres-airflow:
    image: postgres:15
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow123
      - POSTGRES_DB=airflow
    ports:
      - "5433:5432"
    networks:
      - govtrack-network

  airflow-webserver:
    image: apache/airflow:2.5.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow123@postgres-airflow:5432/airflow
      - DATA_PATH=/opt/airflow/data
    ports:
      - "8081:8080"
    depends_on:
      - postgres-airflow
    command: webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
    networks:
      - govtrack-network

  airflow-scheduler:
    image: apache/airflow:2.5.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow123@postgres-airflow:5432/airflow
      - DATA_PATH=/opt/airflow/data
    depends_on:
      - postgres-airflow
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
    networks:
      - govtrack-network

  superset:
    image: apache/superset
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    environment:
      - SUPERSET_SECRET_KEY=govtrack_secret_key
    networks:
      - govtrack-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"
    networks:
      - govtrack-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    networks:
      - govtrack-network

networks:
  govtrack-network:
    driver: bridge