name: dbt parse

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dbt-parse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install dbt-bigquery==1.8.0

      - name: Run dbt parse
        run: |
          cd govtrack_dbt
          dbt parse --profiles-dir .
